export const VeikkausFDEuroTeamMap: Record<string, string> = {
  Albania: "Albania",
  Itävalta: "Austria",
  Belgia: "Belgium",
  Kroatia: "Croatia",
  Tshekki: "Czechia",
  Tanska: "Denmark",
  Englanti: "England",
  Ranska: "France",
  Georgia: "Georgia",
  Saksa: "Germany",
  Unkari: "Hungary",
  Italia: "Italy",
  Hollanti: "Netherlands",
  Puola: "Poland",
  Portugali: "Portugal",
  Romania: "Romania",
  Skotlanti: "Scotland",
  Serbia: "Serbia",
  Slovakia: "Slovakia",
  Slovenia: "Slovenia",
  Espanja: "Spain",
  Sveitsi: "Switzerland",
  Turkki: "Turkey",
  Ukraina: "Ukraine"
};

export const FDVeikkausEuroteamMap: Record<string, string> = {
  Albania: "Albania",
  Austria: "Itävalta",
  Belgium: "Belgia",
  Croatia: "Kroatia",
  Czechia: "Tshekki",
  Denmark: "Tanska",
  England: "Englanti",
  France: "Ranska",
  Georgia: "Georgia",
  Germany: "Saksa",
  Hungary: "Unkari",
  Italy: "Italia",
  Netherlands: "Hollanti",
  Poland: "Puola",
  Portugal: "Portugali",
  Romania: "Romania",
  Scotland: "Skotlanti",
  Serbia: "Serbia",
  Slovakia: "Slovakia",
  Slovenia: "Slovenia",
  Spain: "Espanja",
  Switzerland: "Sveitsi",
  Turkey: "Turkki",
  Ukraine: "Ukraina"
};


export const FDVeikkausPremierLeagueTeamNameMap: Record<string, string> = {
  "AFC Bournemouth": "Bournemouth",
  "Arsenal FC": "Arsenal",
  "Aston Villa FC": "Aston Villa",
  "Aston Villa": "Aston Villa",
  "Brentford FC": "Brentford",
  "Brighton & Hove Albion FC": "Brighton",
  "Brighton Hove": "Brighton",
  "Chelsea FC": "Chelsea",
  "Crystal Palace FC": "Crystal Palace",
  "Crystal Palace": "Crystal Palace",
  "Everton FC": "Everton",
  "Fulham FC": "Fulham",
  "Leeds United FC": "Leeds",
  "Leeds United": "Leeds",
  "Leicester City FC": "Leicester",
  "Leicester City": "Leicester",
  "Liverpool FC": "Liverpool",
  "Man City": "Manchester City",
  "Man United": "Manchester United",
  "Manchester City FC": "Manchester City",
  "Manchester United FC": "Manchester United",
  "Newcastle United FC": "Newcastle",
  "Nottingham Forest FC": "Nottingham Forest",
  "Southampton FC": "Southampton",
  "Tottenham Hotspur FC": "Tottenham",
  "West Ham United FC": "West Ham",
  "West Ham": "West Ham",
  "Wolverhampton Wanderers FC": "Wolverhampton",
  Arsenal: "Arsenal",
  Bournemouth: "Bournemouth",
  Brentford: "Brentford",
  Chelsea: "Chelsea",
  Everton: "Everton",
  Fulham: "Fulham",
  Liverpool: "Liverpool",
  Newcastle: "Newcastle",
  Nottingham: "Nottingham Forest",
  Southampton: "Southampton",
  Tottenham: "Tottenham",
  Wolverhampton: "Wolverhampton",
};

export const FDVeikkausWorldCupTeamMap: Record<string, string> = {
  Qatar: "Qatar",
  Brazil: "Brasilia",
  Belgium: "Belgia",
  France: "Ranska",
  Argentina: "Argentiina",
  England: "Englanti",
  Spain: "Espanja",
  Portugal: "Portugali",
  Mexico: "Meksiko",
  Netherlands: "Hollanti",
  Denmark: "Tanska",
  Germany: "Saksa",
  Uruguay: "Uruguay",
  Switzerland: "Sveitsi",
  "United States": "USA",
  Croatia: "Kroatia",
  Senegal: "Senegal",
  Iran: "Iran",
  Japan: "Japani",
  Morocco: "Marokko",
  Serbia: "Serbia",
  Poland: "Puola",
  "South Korea": "Etelä-Korea",
  Tunisia: "Tunisia",
  Cameroon: "Kamerun",
  Canada: "Kanada",
  Ecuador: "Ecuador",
  "Saudi Arabia": "Saudi-Arabia",
  Ghana: "Ghana",
  Wales: "Wales",
  "Costa Rica": "Costa Rica",
  Australia: "Australia",
  Ukraine: "Ukraina",
  Peru: "Peru",
  Scotland: "Skotlanti",
  "Arab Emirates": "Arabiemiraatit",
};

export const VeikkausFDPremierLeagueTeamMap: Record<string, string> = {
  "Aston Villa": "Aston Villa",
  "Crystal Palace": "Crystal Palace",
  "Manchester City": "Manchester City",
  "Manchester United": "Manchester United",
  "Nottingham Forest": "Nottingham",
  "West Ham": "West Ham",
  Arsenal: "Arsenal",
  Bournemouth: "Bournemouth",
  Brentford: "Brentford",
  Brighton: "Brighton Hove",
  Chelsea: "Chelsea",
  Everton: "Everton",
  Fulham: "Fulham",
  Leeds: "Leeds United",
  Leicester: "Leicester City",
  Liverpool: "Liverpool",
  Newcastle: "Newcastle",
  Southampton: "Southampton",
  Tottenham: "Tottenham",
  Wolverhampton: "Wolverhampton",
};

export const VeikkausFDWorldCupTeamMap: Record<string, string> = {
  Arabiemiraatit: "Arab Emirates",
  Argentiina: "Argentina",
  Australia: "Australia",
  Belgia: "Belgium",
  Brasilia: "Brazil",
  "Costa Rica": "Costa Rica",
  Ecuador: "Ecuador",
  Englanti: "England",
  Espanja: "Spain",
  "Etelä-Korea": "South Korea",
  Ghana: "Ghana",
  Hollanti: "Netherlands",
  Iran: "Iran",
  Japani: "Japan",
  Kamerun: "Cameroon",
  Kanada: "Canada",
  Kroatia: "Croatia",
  Marokko: "Morocco",
  Meksiko: "Mexico",
  Peru: "Peru",
  Portugali: "Portugal",
  Puola: "Poland",
  Qatar: "Qatar",
  Ranska: "France",
  Saksa: "Germany",
  "Saudi-Arabia": "Saudi Arabia",
  Senegal: "Senegal",
  Serbia: "Serbia",
  Skotlanti: "Scotland",
  Sveitsi: "Switzerland",
  Tanska: "Denmark",
  Tunisia: "Tunisia",
  Ukraina: "Ukraine",
  Uruguay: "Uruguay",
  USA: "United States",
  Wales: "Wales",
};
